[
  {
    "url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/pulls/81",
    "id": 1654258737,
    "node_id": "PR_kwDOKasaNs5imfwx",
    "html_url": "https://github.com/chingu-voyages/v46-tier3-team-36/pull/81",
    "diff_url": "https://github.com/chingu-voyages/v46-tier3-team-36/pull/81.diff",
    "patch_url": "https://github.com/chingu-voyages/v46-tier3-team-36/pull/81.patch",
    "issue_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/issues/81",
    "number": 81,
    "state": "closed",
    "locked": false,
    "title": "Attempt at fixing SSE",
    "user": {
      "login": "mpark4656",
      "id": 16367862,
      "node_id": "MDQ6VXNlcjE2MzY3ODYy",
      "avatar_url": "https://avatars.githubusercontent.com/u/16367862?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mpark4656",
      "html_url": "https://github.com/mpark4656",
      "followers_url": "https://api.github.com/users/mpark4656/followers",
      "following_url": "https://api.github.com/users/mpark4656/following{/other_user}",
      "gists_url": "https://api.github.com/users/mpark4656/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mpark4656/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mpark4656/subscriptions",
      "organizations_url": "https://api.github.com/users/mpark4656/orgs",
      "repos_url": "https://api.github.com/users/mpark4656/repos",
      "events_url": "https://api.github.com/users/mpark4656/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mpark4656/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": null,
    "created_at": "2023-12-21T19:49:36Z",
    "updated_at": "2023-12-21T19:49:44Z",
    "closed_at": "2023-12-21T19:49:44Z",
    "merged_at": "2023-12-21T19:49:44Z",
    "merge_commit_sha": "055537b28cb892a7f7cb94ea5c0f7c5b13d5842a",
    "assignee": null,
    "assignees": [

    ],
    "requested_reviewers": [

    ],
    "requested_teams": [

    ],
    "labels": [

    ],
    "milestone": null,
    "draft": false,
    "commits_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/pulls/81/commits",
    "review_comments_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/pulls/81/comments",
    "review_comment_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/issues/81/comments",
    "statuses_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/statuses/e5380010ab41265fb53707ab48376d47e444e14a",
    "head": {
      "label": "chingu-voyages:dev",
      "ref": "dev",
      "sha": "e5380010ab41265fb53707ab48376d47e444e14a",
      "user": {
        "login": "chingu-voyages",
        "id": 45506501,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjQ1NTA2NTAx",
        "avatar_url": "https://avatars.githubusercontent.com/u/45506501?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/chingu-voyages",
        "html_url": "https://github.com/chingu-voyages",
        "followers_url": "https://api.github.com/users/chingu-voyages/followers",
        "following_url": "https://api.github.com/users/chingu-voyages/following{/other_user}",
        "gists_url": "https://api.github.com/users/chingu-voyages/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/chingu-voyages/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/chingu-voyages/subscriptions",
        "organizations_url": "https://api.github.com/users/chingu-voyages/orgs",
        "repos_url": "https://api.github.com/users/chingu-voyages/repos",
        "events_url": "https://api.github.com/users/chingu-voyages/events{/privacy}",
        "received_events_url": "https://api.github.com/users/chingu-voyages/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 699079222,
        "node_id": "R_kgDOKasaNg",
        "name": "v46-tier3-team-36",
        "full_name": "chingu-voyages/v46-tier3-team-36",
        "private": false,
        "owner": {
          "login": "chingu-voyages",
          "id": 45506501,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjQ1NTA2NTAx",
          "avatar_url": "https://avatars.githubusercontent.com/u/45506501?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/chingu-voyages",
          "html_url": "https://github.com/chingu-voyages",
          "followers_url": "https://api.github.com/users/chingu-voyages/followers",
          "following_url": "https://api.github.com/users/chingu-voyages/following{/other_user}",
          "gists_url": "https://api.github.com/users/chingu-voyages/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/chingu-voyages/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/chingu-voyages/subscriptions",
          "organizations_url": "https://api.github.com/users/chingu-voyages/orgs",
          "repos_url": "https://api.github.com/users/chingu-voyages/repos",
          "events_url": "https://api.github.com/users/chingu-voyages/events{/privacy}",
          "received_events_url": "https://api.github.com/users/chingu-voyages/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/chingu-voyages/v46-tier3-team-36",
        "description": "Property Pulse - A property management application that streamlines all aspects of managing rental properties and fosters a harmonious relationship between landlord and tenant. | Voyage-46 | https://chingu.io/ | Twitter: https://twitter.com/ChinguCollabs",
        "fork": false,
        "url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36",
        "forks_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/forks",
        "keys_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/teams",
        "hooks_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/hooks",
        "issue_events_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/issues/events{/number}",
        "events_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/events",
        "assignees_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/assignees{/user}",
        "branches_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/branches{/branch}",
        "tags_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/tags",
        "blobs_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/languages",
        "stargazers_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/stargazers",
        "contributors_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/contributors",
        "subscribers_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/subscribers",
        "subscription_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/subscription",
        "commits_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/contents/{+path}",
        "compare_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/merges",
        "archive_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/downloads",
        "issues_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/issues{/number}",
        "pulls_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/labels{/name}",
        "releases_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/releases{/id}",
        "deployments_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/deployments",
        "created_at": "2023-10-01T21:11:16Z",
        "updated_at": "2023-11-12T21:31:13Z",
        "pushed_at": "2023-12-21T19:49:44Z",
        "git_url": "git://github.com/chingu-voyages/v46-tier3-team-36.git",
        "ssh_url": "git@github.com:chingu-voyages/v46-tier3-team-36.git",
        "clone_url": "https://github.com/chingu-voyages/v46-tier3-team-36.git",
        "svn_url": "https://github.com/chingu-voyages/v46-tier3-team-36",
        "homepage": "https://v46-tier3-team-36-frontend.vercel.app",
        "size": 966,
        "stargazers_count": 1,
        "watchers_count": 1,
        "language": "TypeScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 9,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "hacktoberfest",
          "hacktoberfest2023"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 9,
        "watchers": 1,
        "default_branch": "main"
      }
    },
    "base": {
      "label": "chingu-voyages:main",
      "ref": "main",
      "sha": "ec8b87a5d2fd6c7f59bac77a3312b724b3d329b9",
      "user": {
        "login": "chingu-voyages",
        "id": 45506501,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjQ1NTA2NTAx",
        "avatar_url": "https://avatars.githubusercontent.com/u/45506501?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/chingu-voyages",
        "html_url": "https://github.com/chingu-voyages",
        "followers_url": "https://api.github.com/users/chingu-voyages/followers",
        "following_url": "https://api.github.com/users/chingu-voyages/following{/other_user}",
        "gists_url": "https://api.github.com/users/chingu-voyages/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/chingu-voyages/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/chingu-voyages/subscriptions",
        "organizations_url": "https://api.github.com/users/chingu-voyages/orgs",
        "repos_url": "https://api.github.com/users/chingu-voyages/repos",
        "events_url": "https://api.github.com/users/chingu-voyages/events{/privacy}",
        "received_events_url": "https://api.github.com/users/chingu-voyages/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 699079222,
        "node_id": "R_kgDOKasaNg",
        "name": "v46-tier3-team-36",
        "full_name": "chingu-voyages/v46-tier3-team-36",
        "private": false,
        "owner": {
          "login": "chingu-voyages",
          "id": 45506501,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjQ1NTA2NTAx",
          "avatar_url": "https://avatars.githubusercontent.com/u/45506501?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/chingu-voyages",
          "html_url": "https://github.com/chingu-voyages",
          "followers_url": "https://api.github.com/users/chingu-voyages/followers",
          "following_url": "https://api.github.com/users/chingu-voyages/following{/other_user}",
          "gists_url": "https://api.github.com/users/chingu-voyages/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/chingu-voyages/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/chingu-voyages/subscriptions",
          "organizations_url": "https://api.github.com/users/chingu-voyages/orgs",
          "repos_url": "https://api.github.com/users/chingu-voyages/repos",
          "events_url": "https://api.github.com/users/chingu-voyages/events{/privacy}",
          "received_events_url": "https://api.github.com/users/chingu-voyages/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/chingu-voyages/v46-tier3-team-36",
        "description": "Property Pulse - A property management application that streamlines all aspects of managing rental properties and fosters a harmonious relationship between landlord and tenant. | Voyage-46 | https://chingu.io/ | Twitter: https://twitter.com/ChinguCollabs",
        "fork": false,
        "url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36",
        "forks_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/forks",
        "keys_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/teams",
        "hooks_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/hooks",
        "issue_events_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/issues/events{/number}",
        "events_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/events",
        "assignees_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/assignees{/user}",
        "branches_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/branches{/branch}",
        "tags_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/tags",
        "blobs_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/languages",
        "stargazers_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/stargazers",
        "contributors_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/contributors",
        "subscribers_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/subscribers",
        "subscription_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/subscription",
        "commits_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/contents/{+path}",
        "compare_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/merges",
        "archive_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/downloads",
        "issues_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/issues{/number}",
        "pulls_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/labels{/name}",
        "releases_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/releases{/id}",
        "deployments_url": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/deployments",
        "created_at": "2023-10-01T21:11:16Z",
        "updated_at": "2023-11-12T21:31:13Z",
        "pushed_at": "2023-12-21T19:49:44Z",
        "git_url": "git://github.com/chingu-voyages/v46-tier3-team-36.git",
        "ssh_url": "git@github.com:chingu-voyages/v46-tier3-team-36.git",
        "clone_url": "https://github.com/chingu-voyages/v46-tier3-team-36.git",
        "svn_url": "https://github.com/chingu-voyages/v46-tier3-team-36",
        "homepage": "https://v46-tier3-team-36-frontend.vercel.app",
        "size": 966,
        "stargazers_count": 1,
        "watchers_count": 1,
        "language": "TypeScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 9,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "hacktoberfest",
          "hacktoberfest2023"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 9,
        "watchers": 1,
        "default_branch": "main"
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/pulls/81"
      },
      "html": {
        "href": "https://github.com/chingu-voyages/v46-tier3-team-36/pull/81"
      },
      "issue": {
        "href": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/issues/81"
      },
      "comments": {
        "href": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/issues/81/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/pulls/81/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/pulls/81/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/chingu-voyages/v46-tier3-team-36/statuses/e5380010ab41265fb53707ab48376d47e444e14a"
      }
    },
    "author_association": "CONTRIBUTOR",
    "auto_merge": null,
    "active_lock_reason": null
  }
]
